pipelines:
  - name: build

    triggers:
      - actions:
          - pre-commit

    steps:
      - name: Build
        commands:
          - task --verbose build

  - name: tests

    steps:
      - name: Run unit tests
        commands:
          - echo go test -v ./...

  - name: docs

    triggers:
      - actions:
          - pre-commit

    steps:
      - name: Build documentation pages
        commands:
          - echo task docs
